apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
{{- $files := .Files }}
{{- range $name := tuple "config.ini" "config.yaml" "config.json" }}
{{ $name | indent 2 }}: |-
{{ tpl ($files.Get $name) $ | indent 4 }}
{{- end }}
  config.conf: |-
{{ tpl (.Files.Get "config.conf") . | indent 4 }}