apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    pv: local
spec:
  capacity:
    storage: 1Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # 此处须显式设置空字符串，否则会被设置为默认的 StorageClass
  local:
    path: /root/k8s-local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - aliyun-master-120-79-152-224
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # 此处须显式设置空字符串，否则会被设置为默认的 StorageClass
  selector:
    matchLabels:
      pv: local
