kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # 此处须显式设置空字符串，否则会被设置为默认的 StorageClass
  selector:
    matchLabels:
      pv: local
