apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - port: 3306
      targetPort: mysql
  selector:
    app: mysql
#  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.1
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-root-pass
#                  key: password
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              value: "123456"
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-wordpress-pass
#                  key: password
          ports:
            - containerPort: 3306
              name: mysql
#          volumeMounts:
#            - name: mysql-persistent-storage
#              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: mysql-root-pass
#  labels:
#    app: mysql
#type: Opaque
#data:
#  password: NTQzMjEK # 54321
#
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: mysql-wordpress-pass
#data:
#  password: NTQzMjEK # 54321